### ISSUE TITLE
Node.js 16 deprecation warning

### ISSUE THREAD

**Issue by edmorley** [heroku/use-app-token-action#11]
Using this Action results in the following deprecation warning being shown on the Actions results overview:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: heroku/use-app-token-action@main
```

It sounds like GitHub plans to switch to Node.js 20 on their runners in Spring 2024, at which point I presume this action will break.

See:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

cc @heroku/production-services @heroku/heroku-tools-dx

**Comment by Agony1023** [comment]
Thanks @edmorley! I'll add this to our backlog.

**Comment by edmorley** [comment]
Thank you :-)
