### ISSUE TITLE
Deprecate in favour of the upstream official `actions/create-github-app-token` action?

### ISSUE THREAD

**Issue by edmorley** [heroku/use-app-token-action#16]
GitHub now support similar functionality in an action they maintain:
https://github.com/actions/create-github-app-token

Should this action be deprecated in favour of that?

@Agony1023 @chap @mgomes

**Comment by Agony1023** [comment]
@edmorley I'm so late to this. I'm just seeing it. Yes, yes, and heck yes! 😁 I'm actually working on the deprecation right now.

**Comment by Agony1023** [comment]
Going to link this to the PR (coming soon).

**Comment by mgomes** [comment]
This is awesome! Thanks for the heads up @edmorley
