### ISSUE TITLE
Error when app does not have repository access could be improved

### ISSUE THREAD

**Issue by Malax** [heroku/use-app-token-action#9]
I integrated our bot to another repo and got an error from this action that took me a while to understand. Example run: https://github.com/heroku/webapp-runner/actions/runs/6430765315/job/17462483231

In this case, the app didn't have access to the repo I was using the action in. Maybe we can catch this `NotFound` error and add hint that the app might not have access.

**Comment by Agony1023** [comment]
@Malax Sorry for being a million years late, but we're deprecating this action and recommend using the official [actions/create-github-app-token] action instead.
